sonata_admin:
    title: "TxReplay"
    templates:
        layout: admin/layout.html.twig
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
    security:
        handler: sonata.admin.security.handler.role