sonata_seo:
    encoding:         UTF-8
    page:
        default: sonata.seo.page.default
        title:            Valentin Commenge - Développeur Web
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             valentin commenge txreplay developpeur web symfony symfony2 sensio my little paris mylittleparis france paris php etudiant hetic ecv alternant alternance
                description:          Développeur web à Paris
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Valentin Commenge - Développeur Web
                'og:description':     Développeur web à Paris

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"